language: ruby
rvm:
  - 2.0.0-p353
script:
  - bundle exec rake db:migrate
before_script:
  - cp config/database.travis.yml config/database.yml
  - psql -c 'create database railspeople_test;' -U postgres
