language: ruby
rvm:
  - 1.9.3
script:
  - bundle exec rake db:migrate
  - bundle exec rake db:test:prepare
  - bundle exec rspec spec/
before_script:
  - cp config/database.travis.yml config/database.yml
  - mysql -e 'create database railspeople_test;'