development:
  adapter: mysql2
  encoding: utf8
  database: railspeople_development
  username: root
  password: niema
  host: 127.0.0.1


test:
  adapter: mysql2
  encoding: utf8
  database: railspeople_test
  username: root
  password: niema
  host: 127.0.0.1